org.gradle.jvmargs=-Xmx2G

org.gradle.parallel=false

# Mod Properties
# don't forget to change changelog.md after bumping version
mod_version=6.0.10-beta.1+1.21.8
maven_group=qouteall
archives_base_name=immersive-portals

modmenu_version=15.0.2
cloth_config_version=19.0.147
sodium_path=maven.modrinth:sodium:mc1.21.6-0.6.13-fabric
iris_path=maven.modrinth:iris:1.9.1+1.21.7-fabric
gravity_changer_version=cd4e3377
dimlib_version=1.1.3-beta.1+1.21.8
enable_sodium=true
enable_iris=true
enable_pehkui=false
enable_gravity_changer=false
enable_test_mod=false
enable_geckolib=false

# don't forget to update this if branch changes
git_branch=1.21.8

minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.16.10

# Fabric API
fabric_version=0.136.1+1.21.8

